version: '2'

services:
  wowza:
    restart: always
    build: .
    environment:
      - WOWZA_ACCEPT_LICENSE=yes
      - WOWZA_KEY
    ports:
      - "1935:1935"
      - "8086:8086"
      - "8087:8087"
      - "8088:8088"
      - "8778:8778"
    volumes:
      - wowza_lib:/var/lib/wowza
      - wowza_log:/var/log/wowza

volumes:
  wowza_lib:
  wowza_log:
